controller_list:
  - name: "controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - arm_joint
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
